### ISSUE TITLE
Can't create disk 

### ISSUE THREAD

**Issue by Dinaamagdy** [openvcloud/0-templates#109]
- Try to create disk with the following blueprint : 
```
services:
  - github.com/openvcloud/0-templates/sshkey/0.0.1__014b1608:
       name: '05f48e46'
       dir: '/root/.ssh/'
       passphrase: '014b1608'
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__65403c0f:
      name: 'be-g8-3.demo.greenitglobe.com'
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: ''
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
      provider: itsyouonline
      name: gig_qa_1
      email: dina.magdy.mohammed+123@gmail.com
      openvcloud: 65403c0f

  - github.com/openvcloud/0-templates/account/0.0.1__48c16a1b:
      name: a24d35cb
      openvcloud: 94a9ffb4

  - github.com/openvcloud/0-templates/vdc/0.0.1__c47487bb:
      name: ab8c1de1
      account: 48c16a1b

  - github.com/openvcloud/0-templates/disk/0.0.1__f5d3243c:
      vdc: c47487bb
      disk: 99891974

actions:
  - template: github.com/openvcloud/0-templates/disk/0.0.1
    actions: ['install']
```
## Issue
it returns the following error on  server and disk not created 
```
eff2 - ERROR    - error executing action install:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/openvcloud/0-templates/templates/disk/disk.py", line 105, in install
    self.data['location'] = self.space.model['location']
  File "/opt/code/github/openvcloud/0-templates/templates/disk/disk.py", line 223, in space
    spaceName=vdc
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/OVCClient.py", line 215, in space_get
    raise RuntimeError("name needs to be specified in account in config or on method.")
RuntimeError: name needs to be specified in account in config or on method.
```

**Comment by Dinaamagdy** [comment]
mow , another error happen now, although disk created but can't update it . 
```
[Sun22 09:09] - base.py           :201 :service-a25c8a33-83c9-4c2a-9b2e-3dd83fc08e07 - ERROR    - error executing action install:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/task/task.py", line 78, in execute
    self._result = self.func()
  File "/opt/code/github/openvcloud/0-templates/templates/disk/disk.py", line 141, in install
    self._create()
  File "/opt/code/github/openvcloud/0-templates/templates/disk/disk.py", line 161, in _create
    self._limit_io()
  File "/opt/code/github/openvcloud/0-templates/templates/disk/disk.py", line 259, in _limit_io
    write_iops_sec_max=data['writeIopsSecMax'], size_iops_sec=data['sizeIopsSec']
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 57, in __call__
    raise ApiError(response)
JumpScale9Lib.clients.portal.PortalClient.ApiError: 404 Not Found
Could not find virtual machine beloning to disk

```

**Comment by katia-e** [comment]
@Dinaamagdy ,
* To create a new disk independently from any vm you need to provide `name` field too:
![image](https://user-images.githubusercontent.com/32639869/39566700-c4601206-4ebc-11e8-9e62-f3a7347b0149.png)
* Currently OVC doesn't allow to limit_io on the disks detached from any VM. In order to test update you need to have disk attached. I'll mention it in the doc.
