### ISSUE TITLE
Getting "category actions does not exist" when running the given blueprint

### ISSUE THREAD

**Issue by john-kheir** [openvcloud/0-templates#120]
## Scenario
1- Remove the data repo and and start zrobot server
2- Run the given blueprint 
 
## Blueprint 
```
services:
  - github.com/openvcloud/0-templates/sshkey/0.0.1__5d844cdb:
       name: 'bb601618'
       dir: '/root/.ssh/'
       passphrase: '5d844cdb'
  - github.com/openvcloud/0-templates/openvcloud/0.0.1__a8711d49:
      name: 'be-g8-3.demo.greenitglobe.com'
      address: 'be-g8-3.demo.greenitglobe.com'
      login: 'gig_qa_1@itsyouonline'
      token: '****'
      location: 'be-g8-3'
  - github.com/openvcloud/0-templates/vdcuser/0.0.1__gig_qa_1:
      provider: itsyouonline
      openvcloud: a8711d49
      email: dina.magdy.mohammed+123@gmail.com
      name: gig_qa_1

  - github.com/openvcloud/0-templates/account/0.0.1__28f6c5de:
      openvcloud: 20bac02b
      name: 37a98a21

  - github.com/openvcloud/0-templates/vdc/0.0.1__afa398c4:
      maxNetworkPeerTransfer: 356
      maxMemoryCapacity: 787
      maxCPUCapacity: 542
      account: 28f6c5de
      name: 7c9c44e2
      maxNumPublicIP: 293
      maxVDiskCapacity: 120

  - github.com/openvcloud/0-templates/node/0.0.1__3e85d633:
      vdc: afa398c4
      sshKey: 5d844cdb
      name: 107c6faa

actions:
  - template: github.com/openvcloud/0-templates/vdc/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/vdcuser/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/node/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/account/0.0.1
    actions: ['install']
  - template: github.com/openvcloud/0-templates/openvcloud/0.0.1
    actions: ['install']

```

## Error

```
Traceback (most recent call last):                                                                                                                                                    [59/1543]
  File "/root/0-robot/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/root/0-robot/zerorobot/template/state.py", line 57, in get
    raise StateCategoryNotExistsError("category %s does not exist" % category)
zerorobot.template.state.StateCategoryNotExistsError: category actions does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/openvcloud/0-templates/templates/sshkey/sshkey.py", line 86, in get_info
    self.state.check('actions', 'install', 'ok')
  File "/root/0-robot/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:install:ok failed

* Get OpenvCloud client on URL: be-g8-3.demo.greenitglobe.com
Traceback (most recent call last):
  File "/root/0-robot/zerorobot/template/state.py", line 78, in check
    state = self.get(category, tag)
  File "/root/0-robot/zerorobot/template/state.py", line 57, in get
    raise StateCategoryNotExistsError("category %s does not exist" % category)
zerorobot.template.state.StateCategoryNotExistsError: category actions does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/0-robot/zerorobot/task/task.py", line 79, in execute
    self._result = self._func()
  File "/opt/code/github/openvcloud/0-templates/templates/sshkey/sshkey.py", line 86, in get_info
    self.state.check('actions', 'install', 'ok')
  File "/root/0-robot/zerorobot/template/state.py", line 85, in check
    raise StateCheckError(err_msg)
zerorobot.template.state.StateCheckError: check for state actions:install:ok failed
check for state actions:install:ok failed, Retrying in 3 seconds...
```

**Comment by katia-e** [comment]
@john-kheir , the error occurred because `ssh-service` was not installed

**Comment by john-kheir** [comment]
``` 
 - template: github.com/openvcloud/0-templates/sshkey/0.0.1
    actions: ['install']
```
added this and got exactly the same error
