### ISSUE TITLE
Error while I execute 'create user' template

### ISSUE THREAD

**Issue by islamTaha12** [openvcloud/0-templates#58]
**BluePrint**
```yml
services:
    - github.com/openvcloud/0-templates/openvcloud/0.0.1__myovc:
        location: 'be-g8-3'
        address: 'be-g8-3.greenitglobe.com'
        token: '*************************************************************'
    - github.com/openvcloud/0-templates/vdcuser/0.0.1__adminss:
        openvcloud: myovc
        provider: itsyouonline
        email: test@g.com

actions:
      actions: ['install']

```

```bash
root@vm-2211:/opt/code/github/john-kheir/0-robot6# zrobot server start --listen :6601 --template-repo https://github.com/openvcloud/0-templates --data-repo https://github.com/john-kheir/0-robot6.git
* data directory: /opt/code/github/john-kheir/0-robot6/zrobot_data
* robot running at :6601
* Get OpenvCloud client on URL: be-g8-3.greenitglobe.com
[Fri16 16:25] - base.py           :195 :service-34a1b9b4-0ccd-4872-921e-ac34cf3d5393 - ERROR    - error executing action install:
  File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 375, in get
    return self._raise_exception()
  File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 355, in _raise_exception
    reraise(*self.exc_info)
  File "/usr/local/lib/python3.5/dist-packages/gevent/_compat.py", line 33, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/gevent/threadpool.py", line 211, in _worker
    value = func(*args, **kwargs)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fcfde62d2e8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='be-g8-3.greenitglobe.com', port=443): Max retries exceeded with url: /restmachine/system/docgenerator/prepareCatalog?group=cloudapi (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcfde62d2e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/zerorobot/task/task.py", line 79, in execute
    self._result = self.func()
  File "/opt/code/github/openvcloud/0-templates/templates/vdcuser/vdcuser.py", line 47, in install
    if not client.api.system.usermanager.userexists(name=username):
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/openvcloud/OVCClient.py", line 51, in api
    self._api.load_swagger(group='cloudapi')
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 78, in load_swagger
    swagger = self.system.docgenerator.prepareCatalog(group=group)
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/clients/portal/PortalClient.py", line 53, in __call__
    response = self._session.request(self._method, self._url, kwargs, timeout=300)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='be-g8-3.greenitglobe.com', port=443): Max retries exceeded with url: /restmachine/system/docgenerator/prepareCatalog?group=cloudapi (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcfde62d2e8>: Failed to establish a new connection: [Errno -2] Name or service not known',))


```

**Comment by yveskerwyn** [comment]
Error in template: `address: 'be-g8-3.greenitglobe.com'`

Should be: `address: 'be-g8-3.demo.greenitglobe.com'.
